# Generated by Django 4.0.4 on 2022-07-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spiritual_name',
            field=models.CharField(default='', help_text='Please enter the name you now identify with. \n        Where applicable this will be used as the name by which you are identified in Soul Synthesis.', max_length=200, unique=True),
        ),
    ]
