# Generated by Django 4.0.4 on 2022-07-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_spiritual_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('---', '---'), ('She/her', 'She/her'), ('He/him', 'He/him'), ('They/them', 'They/them'), ('Rather not say', 'Rather not say')], default='---', max_length=20, null=True),
        ),
    ]
