# Generated by Django 4.0.4 on 2022-06-25 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('task_description', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('task_status', models.CharField(choices=[('1) Not started', '1) Not started'), ('2) In progress', '2) In progress'), ('3) Deferred', '3) Deferred'), ('Completed', 'Completed')], default='1) Not started', max_length=20)),
                ('task_priority', models.CharField(choices=[('1) High', '1) High'), ('2) Normal', '2) Normal'), ('3) Low', '3) Low')], default='2) Normal', help_text="Selecting '1) High' will not only place the task higher in the task list but will also result in it showing in the 'My High Priority' section of the dashboard.", max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Enter the date you are aiming to complete this task by.', null=True)),
                ('task_type', models.CharField(choices=[('---', '---'), ('Prepayment', 'Prepayment'), ('Wait List', 'Wait List'), ('Survey', 'Survey'), ('ALAN', 'ALAN'), ('Cancellation Request', 'Cancellation Request'), ('Cancellation Action', 'Cancellation Action')], default='---', max_length=50)),
                ('task_created_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_dear_soul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_task', to='iamown.task')),
            ],
            options={
                'ordering': ['task_status', 'task_priority', 'due_date'],
            },
        ),
    ]
