# Generated by Django 4.0.4 on 2022-06-26 06:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0003_task_assigned_profile_servicegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegroup',
            name='members',
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='purpose',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='qualified_intentions',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
