# Generated by Django 4.0.4 on 2022-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
        ('iamown', '0004_remove_servicegroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='profiles',
            field=models.ManyToManyField(related_name='profiles_in_service_group', to='users.profile'),
        ),
    ]
