# Generated by Django 4.0.4 on 2022-06-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0005_servicegroup_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegroup',
            name='profiles',
        ),
    ]
