# Generated by Django 4.0.4 on 2022-06-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0006_remove_servicegroup_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_dear_soul',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_profile',
        ),
    ]
