# Generated by Django 4.0.4 on 2022-06-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
        ('iamown', '0007_remove_task_assigned_dear_soul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_in_library_task', to='users.profile'),
        ),
    ]
