# Generated by Django 4.0.4 on 2022-06-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
        ('iamown', '0008_task_assigned_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_in_library_task', to='users.profile', verbose_name='Assigned Dear Soul'),
        ),
    ]
