# Generated by Django 4.0.4 on 2022-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
        ('iamown', '0009_alter_task_assigned_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='dear_souls_in_service_group',
            field=models.ManyToManyField(related_name='profiles_in_service_group', to='users.profile', verbose_name='Dear Souls in the service group'),
        ),
    ]
