# Generated by Django 4.0.4 on 2022-06-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0010_servicegroup_dear_souls_in_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_group_assigned_task', to='iamown.servicegroup'),
        ),
    ]
