# Generated by Django 4.0.4 on 2022-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0011_task_assigned_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Library Observation', 'Library Observation')], default='---', max_length=50, null=True),
        ),
    ]
