# Generated by Django 4.0.4 on 2022-06-28 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0015_task_task_outcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_outcome',
            new_name='actions_taken',
        ),
    ]
