# Generated by Django 4.0.4 on 2022-06-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0016_rename_task_outcome_task_actions_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
