# Generated by Django 4.0.4 on 2022-06-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0036_libraryobservation_general_observation_and_more'),
        ('iamown', '0018_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='library_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_record_in_task', to='library.libraryrecord'),
        ),
    ]
