# Generated by Django 4.0.4 on 2022-06-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0019_task_library_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='book_text_impacted',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10, null=True),
        ),
    ]
