# Generated by Django 4.0.4 on 2022-06-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0021_alter_task_book_text_impacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='book_text_impacted',
            field=models.CharField(blank=True, choices=[('---', '---'), ('No', 'No'), ('Yes', 'Yes')], default='---', help_text='Select "Yes" if you believe that the changes made will also need to be made in book files. Select \n        "No" if you believe that this observation only has an impact in the Library Record. For example, if there is \n        a typo where the "ENEDICTION" required correction to "BENEDICTION" then this would unlikely be an error in the \n        book files, and was likely caused by a copy and paste error when the record was uploaded. If you are uncertain \n        if the book text will be impacted select "Yes".', max_length=10, null=True),
        ),
    ]
