# Generated by Django 4.0.4 on 2022-07-01 17:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0022_alter_task_book_text_impacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='library_task_description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='book_text_impacted',
            field=models.CharField(blank=True, choices=[('---', '---'), ('No', 'No'), ('Yes', 'Yes')], default='---', help_text='Select "Yes" if you believe that the changes made will also need to be made in book files. Select \n        "No" if you believe that this observation only has an impact in the Library Record. For example, if a hyperlink \n        is broken this would have no impact upon book copy. If you are uncertain if the book text will be impacted select "Yes".', max_length=10, null=True),
        ),
    ]
