# Generated by Django 4.0.4 on 2022-07-01 17:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0023_task_library_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='library_task_actions_taken',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
