# Generated by Django 4.0.4 on 2022-07-02 00:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0025_task_library_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='book_urls_for_record',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
