# Generated by Django 4.0.4 on 2022-07-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iamown', '0026_task_book_urls_for_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', help_text='Enter the specific task name. This should not be changed once it has been coded into the application as this will be used in task assignment. Do not change this value unless you know what you are doing.', max_length=100, unique=True)),
                ('process_description', tinymce.models.HTMLField(default='', help_text='Enter the process description for the task. Whatever is entered into this field will be the process description provided for the task assignment/notification to the assignee.')),
                ('process_code', models.CharField(blank=True, default='LIB', help_text="Enter the process code for this process activity. The recommended format should be abbreviations of the organization's name and the process name. For example, the Whurthy employee on-boarding process could have the process code of WON. There is a limit of 12 characters for the Process Code.", max_length=12, null=True)),
                ('process_outcome', tinymce.models.HTMLField(blank=True, help_text='If applicable, enter a description of the outcome of this activity.', null=True)),
                ('application', models.CharField(choices=[('Library', 'Library'), ('IAMOWN', 'IAMOWN'), ('Users', 'Users'), ('Other', 'Other')], default='Library', help_text='Please select the application that this entry applies to.', max_length=100)),
                ('relevant_django_file', models.CharField(blank=True, default='events/ views.py', help_text='If applicable, enter the specific file path and file name within the Django web app.', max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsible_for_entry', models.ForeignKey(blank=True, help_text='If applicable, enter the Dear Soul responsible for this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lEE_responsible_for_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LEE',
                'verbose_name_plural': 'LEE',
                'ordering': ['task_name'],
            },
        ),
    ]
