# Generated by Django 4.0.4 on 2022-07-07 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iamown', '0028_alter_lee_process_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEeP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_activity', models.CharField(default='', help_text='Enter the functional activity. Note: the application will only be able to act on this record if the applicable feature has been built into the application. However, please feel free to enter PEeP records for your reference, and to identify future ServiceFlow automation opportunities.', max_length=50, unique=True)),
                ('detailed_description', models.TextField(blank=True, help_text='If applicable, enter a description for this record. While this description will not be utilized directly as a part of a ServiceFlow, providing a description in this field should support understanding when and why this particular record is used, and what ServiceFlow it supports.', null=True)),
                ('process_code', models.CharField(blank=True, default='', help_text="Enter the process code for this process activity. The recommended format should be abbreviations of the organization's name and the process name. For example, the Whurthy employee on-boarding process could have the process code of LFON. There is a limit of 20 characters for the Process Code.", max_length=20, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dear_soul_responsible', models.ForeignKey(help_text='Select the Dear Soul responsible for this task. Please note that this required field is integral to ServiceFlow automation in that information in both this field and Process function is used to, where appropriate, assign tasks as a part of ServiceFlow.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_group', models.ForeignKey(blank=True, help_text='If this PEeP entry belongs to a ServiceFlow associated with a Service Group then select them. This field is optional and is use for reference only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_group_in_PEeP', to='iamown.servicegroup')),
            ],
            options={
                'verbose_name': 'PEeP',
                'verbose_name_plural': 'PEeP',
                'ordering': ['functional_activity'],
            },
        ),
    ]
