# Generated by Django 4.0.4 on 2022-07-08 00:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0029_peep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peep',
            name='detailed_description',
            field=tinymce.models.HTMLField(blank=True, help_text='If applicable, enter a description for this record. While this description will not be utilized directly as a part of a ServiceFlow, providing a description in this field should support understanding when and why this particular record is used, and what ServiceFlow it supports.', null=True),
        ),
    ]
