# Generated by Django 4.0.4 on 2022-07-08 20:28

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0030_alter_peep_detailed_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(help_text='Enter the audience name.', max_length=100, unique=True)),
                ('audience_notes', tinymce.models.HTMLField(blank=True, help_text='If applicable, enter any notes about this audience.', null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
