# Generated by Django 4.0.4 on 2022-07-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0032_mailinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'Mailing List', 'verbose_name_plural': 'Mailing List'},
        ),
    ]
