# Generated by Django 4.0.4 on 2022-07-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0034_audience_scope_alter_lee_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='audience',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='audience_in_mailing_list', to='iamown.audience'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='subscribed',
            field=models.CharField(blank=True, choices=[('---', '---'), ('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=10, null=True),
        ),
    ]
