# Generated by Django 4.0.4 on 2022-07-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iamown', '0035_alter_mailinglist_audience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Enter a subject for the email campaign. Note that in the interest of readability that the subject is limited to 60 characters.', max_length=60, null=True)),
                ('message', tinymce.models.HTMLField(blank=True, help_text='Enter the email message you intend on sending.', null=True)),
                ('email_send_log', tinymce.models.HTMLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('audience', models.ForeignKey(default='', help_text='Select the targeted audience for this email campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='audience_in_email_campaign', to='iamown.audience')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Campaigns',
                'verbose_name_plural': 'Email Campaign',
            },
        ),
    ]
