# Generated by Django 4.0.4 on 2022-07-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0037_emailcampaign_send_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'ordering': ['-date_created'], 'verbose_name': 'Email Campaigns', 'verbose_name_plural': 'Email Campaign'},
        ),
    ]
