# Generated by Django 4.0.4 on 2022-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0039_alter_emailcampaign_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='ready_to_send',
            field=models.CharField(blank=True, choices=[('---', '---'), ('No', 'No'), ('Yes', 'Yes')], default='No', help_text='By default, this is set to "No". When you are ready to begin the Email Campaign ServiceFlow then change this to "Yes".', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Library Observation', 'Library Observation'), ('Book Edit', 'Book Edit'), ('Email Campaign', 'Email Campaign')], default='---', max_length=50, null=True),
        ),
    ]
