# Generated by Django 4.0.4 on 2022-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0040_emailcampaign_ready_to_send_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='ready_to_send',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', help_text='By default, this is set to "No". When you are ready to begin the Email Campaign ServiceFlow then change this to "Yes".', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='subscribed',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='book_text_impacted',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='---', help_text='Select "Yes" if you believe that the changes made will also need to be made in book files. Select \n        "No" if you believe that this observation only has an impact in the Library Record. For example, if a hyperlink \n        is broken this would have no impact upon book copy. If you are uncertain if the book text will be impacted select "Yes".', max_length=10, null=True),
        ),
    ]
