# Generated by Django 4.0.4 on 2022-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0041_alter_emailcampaign_ready_to_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='test_email_sent',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10, null=True),
        ),
    ]
