# Generated by Django 4.0.4 on 2022-07-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0042_emailcampaign_test_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='sender_accepted_test',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='ready_to_send',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', help_text='By default, this is set to "No". When you are ready to begin the Email Campaign ServiceFlow then change this to "Yes".', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='test_email_sent',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
    ]
