# Generated by Django 4.0.4 on 2022-07-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0043_emailcampaign_sender_accepted_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign_in_task', to='iamown.emailcampaign'),
        ),
    ]
