# Generated by Django 4.0.4 on 2022-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0045_task_decision_task_decision_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'ordering': ['send_status'], 'verbose_name': 'Email Campaigns', 'verbose_name_plural': 'Email Campaign'},
        ),
        migrations.AlterField(
            model_name='task',
            name='decision',
            field=models.CharField(choices=[('---', '---'), ('Agreed', 'Agreed'), ('Revise', 'Revise'), ('Decline', 'Decline')], default='---', help_text='\n        Select "Agreed" to indicate you are in Agreement with what has been proposed in this ServiceFlow.\n\n        Select "Declined" to indicate that you are not in Agreement.', max_length=20),
        ),
    ]
