# Generated by Django 4.0.4 on 2022-07-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0047_alter_task_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='book_text_impacted',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default='No', help_text='Select "Yes" if you believe that the changes made will also need to be made in book files. \n\n        Select "No" if you believe that this observation only has an impact in the Library Record. For example, if a \n        hyperlink is broken this would have no impact upon book copy. \nIf you are uncertain if the book text will be \n        impacted select "Yes".', max_length=10, null=True),
        ),
    ]
