# Generated by Django 4.0.4 on 2022-07-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0049_alter_task_decision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'ordering': ['-subscribed', 'audience', 'user', 'email'], 'verbose_name': 'Mailing List', 'verbose_name_plural': 'Mailing List'},
        ),
    ]
