# Generated by Django 4.0.4 on 2022-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0052_alter_peep_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_campaign_test_accepted',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
    ]
