# Generated by Django 4.0.4 on 2022-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0054_alter_task_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='number_of_accepted_reviews',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='number_of_declined_reviews',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='number_of_reviewers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='review_email_sent',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
    ]
