# Generated by Django 4.0.4 on 2022-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0062_mailinglist_mailing_list_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
