# Generated by Django 4.0.4 on 2022-07-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0063_alter_mailinglist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
