# Generated by Django 4.0.4 on 2022-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0064_alter_mailinglist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='audience',
            field=models.CharField(help_text='Newsletter.', max_length=100, unique=True),
        ),
    ]
