# Generated by Django 4.0.4 on 2022-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0065_alter_audience_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='subscribed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Unconfirmed', 'Unconfirmed'), ('No', 'No')], default='Yes', max_length=20),
        ),
    ]
