# Generated by Django 4.0.4 on 2022-07-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0066_alter_mailinglist_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
    ]
