# Generated by Django 4.0.4 on 2022-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0067_alter_mailinglist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
