# Generated by Django 4.0.4 on 2022-07-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0068_emailcampaign_date_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audience',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='audience',
            name='ordering',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='audience',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
