# Generated by Django 4.0.4 on 2022-07-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0069_alter_audience_options_audience_ordering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'ordering': ['audience', 'subscribed', 'user', 'email'], 'verbose_name': 'Mailing List', 'verbose_name_plural': 'Mailing List'},
        ),
    ]
