# Generated by Django 4.0.4 on 2022-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamown', '0070_alter_mailinglist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Library Task', 'Library Task'), ('Decision', 'Decision'), ('Library Observation', 'Library Observation'), ('Book Edit', 'Book Edit'), ('Email Campaign', 'Email Campaign'), ('Email Campaign 2', 'Email Campaign 2'), ('Email Campaign 2 - Revise', 'Email Campaign 2 - Revise')], default='---', max_length=50, null=True),
        ),
    ]
