version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - static_volume:/app/web/build/staticfiles
      - ./temp:/app/web/data
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/web/build/staticfiles
    ports:
      - 443:4000
      - 80:3999
    depends_on:
      - web

volumes:
  static_volume: